/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author rogerio
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        alunoMenuItem = new javax.swing.JMenuItem();
        turmaMenuItem = new javax.swing.JMenuItem();
        usuarioMenuItem = new javax.swing.JMenuItem();
        matriculaMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro");
        setLocationByPlatform(true);
        setResizable(false);

        desktopPane.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        jLabel2.setForeground(java.awt.Color.cyan);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LogoAtualv6.jpg"))); // NOI18N
        desktopPane.add(jLabel2);
        jLabel2.setBounds(10, 20, 650, 420);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastros");

        alunoMenuItem.setMnemonic('o');
        alunoMenuItem.setText("Aluno");
        alunoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(alunoMenuItem);

        turmaMenuItem.setMnemonic('s');
        turmaMenuItem.setText("Turma");
        turmaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(turmaMenuItem);

        usuarioMenuItem.setText("Usuário");
        usuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(usuarioMenuItem);

        matriculaMenuItem1.setText("Matricula");
        matriculaMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(matriculaMenuItem1);

        menuBar.add(fileMenu);

        jMenu1.setText("Chamada");
        menuBar.add(jMenu1);

        jMenu2.setText("Ferramentas");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alunoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoMenuItemActionPerformed
      CadastroAlunoView alunoView= new CadastroAlunoView();
      this.desktopPane.add(alunoView);
      alunoView.setVisible(true);
      
    }//GEN-LAST:event_alunoMenuItemActionPerformed

    private void turmaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaMenuItemActionPerformed
        CadastroTurmaView turmaView= new CadastroTurmaView();
      this.desktopPane.add(turmaView);
      turmaView.setVisible(true);
    }//GEN-LAST:event_turmaMenuItemActionPerformed

    private void usuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioMenuItemActionPerformed
         CadastroUsuarioView loginView= new CadastroUsuarioView();
      this.desktopPane.add(loginView);
      loginView.setVisible(true);
    }//GEN-LAST:event_usuarioMenuItemActionPerformed

    private void matriculaMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaMenuItem1ActionPerformed
       CadastroMatriculaView  matriculaView= new CadastroMatriculaView();
      this.desktopPane.add(matriculaView);
      matriculaView.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_matriculaMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     /*   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(false);
            }
        });

    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alunoMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem matriculaMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem turmaMenuItem;
    private javax.swing.JMenuItem usuarioMenuItem;
    // End of variables declaration//GEN-END:variables

}
